org: iamamash
app: serverless-taskmaster-aws-app
service: serverless-taskmaster-aws-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:042770045671:table/insertion

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: get
  insertData:
    handler: src/insertData.handler
    events:
      - httpApi:
          path: /data
          method: post
  getData:
    handler: src/getData.handler
    events:
      - httpApi:
          path: /data
          method: get
  updateData:
    handler: src/updateData.handler
    events:
      - httpApi:
          path: /data/{id}
          method: put

resources:
  Resources:
    insertData:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: insertion
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
